name: TagBot
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0,12 * * *
jobs:
  TagBot:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: skleinbo/JuliaRegistry.jl
